import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const milling = localFont({
  src: './assets/milling.otf',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={milling.className}>{children}</body>
    </html>
  );
}
